### ISSUE TITLE
[DEV Branch] Update Hammer Shaded preview mode like CS:GO.

### ISSUE THREAD

**Issue by THS2121966** [SCell555/sdk-2013-hammer#10]
This realisation have one issue - preview bug with "sky" shader but sometimes with other shader like "worldvertextransition". And CS:GO Hammer Shaded preview looks more smoothly like "phong" lighting.
![123](https://user-images.githubusercontent.com/56027883/98838919-165b8b00-246f-11eb-97b8-28dc64d3f3c8.PNG)

https://youtu.be/JiKWVVXij5o

**Comment by SCell555** [comment]
This is done inside shaders. This is out of scope of this project.
