### ISSUE TITLE
[Idea] Leaked  2003 Hammer -> Hammer 2013 and Foundry

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [SCell555/sdk-2013-hammer#2]
well this will sounds odd but why not try to port features that originally where in the 2003 hammer (the possibility to creathing moving objects whit frames, ects)

also what about the ingame tool called foundry? i know that is too much  but in 2007 leak there's the foundry source and will be good if you merge the foundry tool into hammer_dll

**Comment by SCell555** [comment]
This needs engine integration. Out of scope of this project.
