### ISSUE TITLE
[DEV Branch] Hammer shutting down after entity animation preview selected loop animation.

### ISSUE THREAD

**Issue by THS2121966** [SCell555/sdk-2013-hammer#9]
Hammer shutting down if in entity animation preview selected loop animation like walk cycle.
================================================================
https://1drv.ms/u/s!AmeHDHSWg_2EqTXvlV2k_w0Z8JbL?e=LQe3QR

**Comment by THS2121966** [comment]
![123](https://user-images.githubusercontent.com/56027883/98702682-e6e04c00-23a4-11eb-9578-db27d76853d4.PNG)

**Comment by SCell555** [comment]
Fixed
